#!/bin/bash
rm resultados.txt
rm errores.txt
for j in {5..15}
do
   rm nid$j.txt
  rm pos$j.txt
	rm end$j.txt

	for i in {1..18}
	do
		 rm nid$j-$i.txt
		 rm pos$j-$i.txt
		 rm end$j-$i.txt
	   ./prueba.py $j $i
		 cat nid$j-$i.txt >> nid$j.txt
		 cat pos$j-$i.txt >> pos$j.txt
		 cat end$j-$i.txt >> end$j.txt
		 rm nid$j-$i.txt
		 rm end$j-$i.txt
	   rm pos$j-$i.txt
	done
done
