#!/bin/bash
rm resultados.txt
for j in {19..30}
do
	rm resultados$j.txt
	echo "0" >> resultados$j.txt

	for i in {1..10}
	do
	   ./top_block.py $j
	done
	echo $j >> resultados.txt
	echo ',' >> resultados.txt
	cat resultados$j.txt >> resultados.txt
	echo ',' >> resultados.txt
	rm resultados$j.txt
done
